#!/usr/bin/env python3
"""
translate-root-ca-to-es.py
==========================

Traduce los archivos HTML del árbol raíz (excluyendo /ca/, /en/) que tengan
lang="ca" al castellano. Las matemáticas (LaTeX/KaTeX entre $...$, $$...$$)
y los atributos HTML (class, id, href, etc.) se preservan intactos.

Usa un diccionario CA→ES amplio orientado a contenido educativo matemático.

NO produce traducción perfecta — los archivos más visibles deberían revisarse
manualmente. Pero deja la base en castellano correcta.

Uso:
    python3 scripts/translate-root-ca-to-es.py [--dry-run]
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKIP_TOP = {"ca", "en", "templates", "scripts", "node_modules", ".git", "outputs"}
DRY_RUN = "--dry-run" in sys.argv

# Diccionario CA→ES (ordenado: primero frases largas, luego palabras sueltas).
# Las claves son case-sensitive: incluimos versiones en mayúsculas/capitalizadas
# por separado para evitar transformar p.ej. "Apunts" en "apuntes".
GLOSSARY = [
    # ───── FRASES COMPLETAS ─────
    ("Apunts de classe en català", "Apuntes de clase en castellano"),
    ("Es publiquen per apartats a mesura que avança la unitat", "Se publican por apartados a medida que avanza la unidad"),
    ("Inclou exemple guiat", "Incluye ejemplo guiado"),
    ("amb solució amagada", "con solución oculta"),
    ("amb solució desplegable", "con solución desplegable"),
    ("Apunts de Mat. Aplicades", "Apuntes de Mat. Aplicadas"),
    ("Apunts de la unitat de", "Apuntes de la unidad de"),
    ("Apunts complets de la unitat", "Apuntes completos de la unidad"),
    ("Comencem els apunts", "Empezamos los apuntes"),
    ("Per a cada parell", "Para cada par"),
    ("per a tot", "para todo"),
    ("Per què", "Por qué"),
    ("Pot ser", "Puede ser"),
    ("Es desconeix", "Se desconoce"),
    ("Es nota", "Se denota"),
    ("Sigui", "Sea"),
    ("Sigueu", "Sean"),
    ("Es llança", "Se lanza"),
    ("S'anomena", "Se llama"),
    ("amb solució oculta", "con solución oculta"),
    ("apartat següent", "apartado siguiente"),
    ("Apartat següent", "Apartado siguiente"),
    ("Apartat anterior", "Apartado anterior"),
    ("Índex de la unitat", "Índice de la unidad"),
    ("Navegació dels apunts", "Navegación de los apuntes"),
    ("nombre d'èxits", "número de éxitos"),
    ("Quina és la probabilitat", "Cuál es la probabilidad"),
    ("De quantes maneres", "De cuántas maneras"),
    ("almenys", "al menos"),
    ("almenys un", "al menos uno"),
    ("almenys una", "al menos una"),
    ("Almenys", "Al menos"),
    ("a la suerte", "al azar"),
    ("a l'atzar", "al azar"),
    ("l'atzar", "el azar"),
    ("d'èxit i fracàs", "de éxito y fracaso"),
    ("èxit / fracàs", "éxito / fracaso"),
    ("èxit o fracàs", "éxito o fracaso"),
    ("una variable aleatòria discreta", "una variable aleatoria discreta"),
    ("variable aleatòria discreta", "variable aleatoria discreta"),
    ("Variable aleatòria discreta", "Variable aleatoria discreta"),
    ("variable aleatòria", "variable aleatoria"),
    ("Variable aleatòria", "Variable aleatoria"),
    ("nombres combinatoris", "números combinatorios"),
    ("Nombres combinatoris", "Números combinatorios"),
    ("nombre combinatori", "número combinatorio"),
    ("nombre combinat", "número combinatorio"),
    ("desviació típica", "desviación típica"),
    ("Desviació típica", "Desviación típica"),
    ("funció de probabilitat", "función de probabilidad"),
    ("Funció de probabilitat", "Función de probabilidad"),
    ("Funció candidata", "Función candidata"),
    ("probabilitat composta", "probabilidad compuesta"),
    ("Probabilitat composta", "Probabilidad compuesta"),
    ("probabilitat condicionada", "probabilidad condicionada"),
    ("regla del producte", "regla del producto"),
    ("Regla del producte", "Regla del producto"),
    ("regla de la suma", "regla de la suma"),
    ("Regla de la suma", "Regla de la suma"),
    ("tipus d'esdeveniments", "tipos de eventos"),
    ("Tipus d'esdeveniments", "Tipos de eventos"),
    ("esdeveniments compatibles", "eventos compatibles"),
    ("Esdeveniments compatibles", "Eventos compatibles"),
    ("esdeveniments incompatibles", "eventos incompatibles"),
    ("esdeveniments dependents", "eventos dependientes"),
    ("esdeveniments independents", "eventos independientes"),
    ("dependents vs independents", "dependientes vs independientes"),
    ("compatibles vs incompatibles", "compatibles vs incompatibles"),
    ("amb reposició", "con reposición"),
    ("Amb reposició", "Con reposición"),
    ("sense reposició", "sin reposición"),
    ("Sense reposició", "Sin reposición"),
    ("amb i sense reposició", "con y sin reposición"),
    ("teorema de Bayes", "teorema de Bayes"),
    ("teorema de la probabilitat total", "teorema de la probabilidad total"),
    ("probabilitat total i Bayes", "probabilidad total y Bayes"),
    ("operacions amb conjunts", "operaciones con conjuntos"),
    ("Operacions amb conjunts", "Operaciones con conjuntos"),
    ("llei de Laplace", "ley de Laplace"),
    ("Llei de Laplace", "Ley de Laplace"),
    ("definicions prèvies", "definiciones previas"),
    ("Definicions prèvies", "Definiciones previas"),
    ("equacions racionals", "ecuaciones racionales"),
    ("equacions irracionals", "ecuaciones irracionales"),
    ("equacions bicuadrades", "ecuaciones bicuadradas"),
    ("equacions exponencials", "ecuaciones exponenciales"),
    ("equacions logarítmiques", "ecuaciones logarítmicas"),
    ("equacions i sistemes", "ecuaciones y sistemas"),
    ("inequacions", "inecuaciones"),
    ("Inequacions", "Inecuaciones"),
    ("polinomis", "polinomios"),
    ("Polinomis", "Polinomios"),
    ("nombres reals", "números reales"),
    ("Nombres reals", "Números reales"),
    ("funcions reals", "funciones reales"),
    ("Funcions reals", "Funciones reales"),
    ("funcions i domini", "funciones y dominio"),
    ("estudi i representació", "estudio y representación"),
    ("imatges i antiimatges", "imágenes y antiimágenes"),
    ("Imatges i antiimatges", "Imágenes y antiimágenes"),
    ("derivada d'una funció", "derivada de una función"),
    ("Derivada d'una funció", "Derivada de una función"),
    ("fraccions", "fracciones"),
    ("Fraccions", "Fracciones"),
    ("fraccions equivalents", "fracciones equivalentes"),
    ("cossos de revolució", "cuerpos de revolución"),
    ("Cossos de revolució", "Cuerpos de revolución"),
    ("nombres fraccionaris", "números fraccionarios"),
    ("Nombres fraccionaris", "Números fraccionarios"),
    ("Mat. Aplicades CCSS 1r BTL", "Mat. Aplicadas CCSS 1º BTL"),
    ("Mat. Aplicades", "Mat. Aplicadas"),
    ("1r BTL CCSS", "1º BTL CCSS"),
    ("1r BTL", "1º BTL"),
    ("2n BTL", "2º BTL"),
    ("2n ESO", "2º ESO"),
    ("3r ESO", "3º ESO"),
    ("4t ESO", "4º ESO"),
    ("1r ESO", "1º ESO"),
    # ───── PALABRAS SUELTAS ─────
    ("Apunts", "Apuntes"),
    ("apunts", "apuntes"),
    ("Exercicis", "Ejercicios"),
    ("exercicis", "ejercicios"),
    ("Exercici", "Ejercicio"),
    ("exercici", "ejercicio"),
    ("Exemple", "Ejemplo"),
    ("exemple", "ejemplo"),
    ("Exemples", "Ejemplos"),
    ("exemples", "ejemplos"),
    ("Solució", "Solución"),
    ("solució", "solución"),
    ("Solucions", "Soluciones"),
    ("solucions", "soluciones"),
    ("Definició", "Definición"),
    ("definició", "definición"),
    ("Definicions", "Definiciones"),
    ("definicions", "definiciones"),
    ("Demostració", "Demostración"),
    ("demostració", "demostración"),
    ("Teorema", "Teorema"),
    ("teorema", "teorema"),
    ("Equació", "Ecuación"),
    ("equació", "ecuación"),
    ("Equacions", "Ecuaciones"),
    ("equacions", "ecuaciones"),
    ("Inequació", "Inecuación"),
    ("inequació", "inecuación"),
    ("Sistema", "Sistema"),
    ("sistemes", "sistemas"),
    ("Sistemes", "Sistemas"),
    ("Funció", "Función"),
    ("funció", "función"),
    ("Funcions", "Funciones"),
    ("funcions", "funciones"),
    ("Conjunt", "Conjunto"),
    ("conjunt", "conjunto"),
    ("Conjunts", "Conjuntos"),
    ("conjunts", "conjuntos"),
    ("Probabilitat", "Probabilidad"),
    ("probabilitat", "probabilidad"),
    ("Probabilitats", "Probabilidades"),
    ("probabilitats", "probabilidades"),
    ("Distribució", "Distribución"),
    ("distribució", "distribución"),
    ("Distribucions", "Distribuciones"),
    ("distribucions", "distribuciones"),
    ("Binomial", "Binomial"),
    ("binomial", "binomial"),
    ("Esperança", "Esperanza"),
    ("esperança", "esperanza"),
    ("Variància", "Varianza"),
    ("variància", "varianza"),
    ("Mitjana", "Media"),
    ("mitjana", "media"),
    ("Esdeveniment", "Evento"),
    ("esdeveniment", "evento"),
    ("Esdeveniments", "Eventos"),
    ("esdeveniments", "eventos"),
    ("Successos", "Sucesos"),
    ("successos", "sucesos"),
    ("Successió", "Sucesión"),
    ("Cardinal", "Cardinal"),
    ("cardinal", "cardinal"),
    ("Espai mostral", "Espacio muestral"),
    ("espai mostral", "espacio muestral"),
    ("Discreta", "Discreta"),
    ("discreta", "discreta"),
    ("Discret", "Discreto"),
    ("discret", "discreto"),
    ("Contínua", "Continua"),
    ("contínua", "continua"),
    ("Continu", "Continuo"),
    ("continu", "continuo"),
    ("Bernoulli", "Bernoulli"),
    ("èxit", "éxito"),
    ("Èxit", "Éxito"),
    ("èxits", "éxitos"),
    ("fracàs", "fracaso"),
    ("Fracàs", "Fracaso"),
    ("fracasos", "fracasos"),
    ("Número", "Número"),
    ("Nombre", "Número"),
    ("nombre", "número"),
    ("Nombres", "Números"),
    ("nombres", "números"),
    ("Cara", "Cara"),
    ("cara", "cara"),
    ("Cares", "Caras"),
    ("Creu", "Cruz"),
    ("creu", "cruz"),
    ("Dau", "Dado"),
    ("dau", "dado"),
    ("Daus", "Dados"),
    ("daus", "dados"),
    ("Moneda", "Moneda"),
    ("Llançament", "Lanzamiento"),
    ("llançament", "lanzamiento"),
    ("Penal", "Penalti"),
    ("penal", "penalti"),
    ("Penals", "Penaltis"),
    ("penals", "penaltis"),
    ("Bola", "Bola"),
    ("Boles", "Bolas"),
    ("boles", "bolas"),
    ("Vermella", "Roja"),
    ("vermella", "roja"),
    ("Vermelles", "Rojas"),
    ("vermelles", "rojas"),
    ("Blanca", "Blanca"),
    ("blanca", "blanca"),
    ("Blanques", "Blancas"),
    ("blanques", "blancas"),
    ("Negra", "Negra"),
    ("negra", "negra"),
    ("Negres", "Negras"),
    ("negres", "negras"),
    ("Urna", "Urna"),
    ("urna", "urna"),
    ("Baralla espanyola", "Baraja española"),
    ("baralla espanyola", "baraja española"),
    ("baralla", "baraja"),
    ("Cartes", "Cartas"),
    ("cartes", "cartas"),
    ("Carta", "Carta"),
    ("carta", "carta"),
    ("Or", "Oro"),
    ("Ors", "Oros"),
    ("Espases", "Espadas"),
    ("Bastos", "Bastos"),
    ("Copes", "Copas"),
    ("Bombetes", "Bombillas"),
    ("bombetes", "bombillas"),
    ("Aprovar", "Aprobar"),
    ("aprovar", "aprobar"),
    ("Suspendre", "Suspender"),
    ("suspendre", "suspender"),
    ("Aprovat", "Aprobado"),
    ("aprovat", "aprobado"),
    ("Aprovats", "Aprobados"),
    ("aprovats", "aprobados"),
    ("Suspès", "Suspenso"),
    ("suspès", "suspenso"),
    ("Suspesos", "Suspensos"),
    ("suspesos", "suspensos"),
    ("Suspengui", "Suspenda"),
    ("suspenguin", "suspendan"),
    ("alumnat", "alumnado"),
    ("Alumnat", "Alumnado"),
    ("Estudiant", "Estudiante"),
    ("estudiant", "estudiante"),
    ("Estudiants", "Estudiantes"),
    ("estudiants", "estudiantes"),
    ("Curs", "Curso"),
    ("curs", "curso"),
    ("Cursos", "Cursos"),
    ("Cursos passats", "Cursos pasados"),
    ("curs passat", "curso pasado"),
    ("triats", "elegidos"),
    ("Triats", "Elegidos"),
    ("triat", "elegido"),
    ("Filosofia", "Filosofía"),
    ("filosofia", "filosofía"),
    ("Institut", "Instituto"),
    ("institut", "instituto"),
    ("Grup", "Grupo"),
    ("grup", "grupo"),
    ("Grups", "Grupos"),
    ("grups", "grupos"),
    ("Hagin", "Hayan"),
    ("hagin", "hayan"),
    ("hagi", "haya"),
    ("Vegada", "Vez"),
    ("vegada", "vez"),
    ("Vegades", "Veces"),
    ("vegades", "veces"),
    ("repeticions", "repeticiones"),
    ("Repeticions", "Repeticiones"),
    ("repetir", "repetir"),
    ("Repetir", "Repetir"),
    ("Llançar", "Lanzar"),
    ("llançar", "lanzar"),
    ("Llança", "Lanza"),
    ("llança", "lanza"),
    ("Llançat", "Lanzado"),
    ("Treure", "Sacar"),
    ("treure", "sacar"),
    ("Treuen", "Sacan"),
    ("treuen", "sacan"),
    ("Treuran", "Sacarán"),
    ("Trien", "Eligen"),
    ("Triar", "Elegir"),
    ("triar", "elegir"),
    ("Comptar", "Contar"),
    ("comptar", "contar"),
    ("Comptar el nombre", "Contar el número"),
    ("Calcula", "Calcula"),
    ("calcula", "calcula"),
    ("Calcular", "Calcular"),
    ("calcular", "calcular"),
    ("Calculem", "Calculamos"),
    ("calculem", "calculamos"),
    ("Determina", "Determina"),
    ("Identifica", "Identifica"),
    ("identifica", "identifica"),
    ("Justifica", "Justifica"),
    ("justifica", "justifica"),
    ("Considera", "Considera"),
    ("considera", "considera"),
    ("Comprovació", "Comprobación"),
    ("comprovació", "comprobación"),
    ("comprovar", "comprobar"),
    ("Comprova", "Comprueba"),
    ("comprova", "comprueba"),
    ("Trobeu", "Encontrad"),
    ("Trobar", "Encontrar"),
    ("trobar", "encontrar"),
    ("Resol", "Resuelve"),
    ("resol", "resuelve"),
    ("Resoldre", "Resolver"),
    ("resoldre", "resolver"),
    ("Veure", "Ver"),
    ("veure", "ver"),
    ("Veiem", "Vemos"),
    ("veiem", "vemos"),
    ("Veurem", "Veremos"),
    ("veurem", "veremos"),
    ("així doncs", "así pues"),
    ("Així doncs", "Así pues"),
    ("Així", "Así"),
    ("així", "así"),
    ("Aquests", "Estos"),
    ("aquests", "estos"),
    ("Aquestes", "Estas"),
    ("aquestes", "estas"),
    ("Aquest", "Este"),
    ("aquest", "este"),
    ("Aquesta", "Esta"),
    ("aquesta", "esta"),
    ("aquell", "aquel"),
    ("aquella", "aquella"),
    ("aquells", "aquellos"),
    ("Però", "Pero"),
    ("però", "pero"),
    ("Sense", "Sin"),
    ("sense", "sin"),
    ("També", "También"),
    ("també", "también"),
    ("Només", "Solo"),
    ("només", "solo"),
    ("Llavors", "Entonces"),
    ("llavors", "entonces"),
    ("Aleshores", "Entonces"),
    ("aleshores", "entonces"),
    ("Sempre", "Siempre"),
    ("sempre", "siempre"),
    ("Mai", "Nunca"),
    ("mai", "nunca"),
    ("Tot", "Todo"),
    ("tot", "todo"),
    ("Totes", "Todas"),
    ("totes", "todas"),
    ("Tots", "Todos"),
    ("tots", "todos"),
    ("Tota", "Toda"),
    ("tota", "toda"),
    ("Algú", "Alguien"),
    ("algú", "alguien"),
    ("Quin", "Qué"),
    ("quin", "qué"),
    ("Quina", "Qué"),
    ("quina", "qué"),
    ("Quins", "Qué"),
    ("quins", "qué"),
    ("Quines", "Qué"),
    ("quines", "qué"),
    ("Mostra", "Muestra"),
    ("mostra", "muestra"),
    ("Mostrar", "Mostrar"),
    ("Cinquè", "Quinto"),
    ("cinquè", "quinto"),
    ("Sisè", "Sexto"),
    ("sisè", "sexto"),
    ("Setè", "Séptimo"),
    ("setè", "séptimo"),
    ("Vuitè", "Octavo"),
    ("vuitè", "octavo"),
    ("Novè", "Noveno"),
    ("novè", "noveno"),
    ("Desè", "Décimo"),
    ("desè", "décimo"),
    ("Primer", "Primer"),
    ("primer", "primer"),
    ("Primera", "Primera"),
    ("primera", "primera"),
    ("Segon", "Segundo"),
    ("segon", "segundo"),
    ("Segona", "Segunda"),
    ("segona", "segunda"),
    ("Tercer", "Tercer"),
    ("tercer", "tercer"),
    ("Tercera", "Tercera"),
    ("tercera", "tercera"),
    ("Quart", "Cuarto"),
    ("quart", "cuarto"),
    ("Quarta", "Cuarta"),
    ("quarta", "cuarta"),
    ("Apartat", "Apartado"),
    ("apartat", "apartado"),
    ("Apartats", "Apartados"),
    ("apartats", "apartados"),
    ("Unitat", "Unidad"),
    ("unitat", "unidad"),
    ("Unitats", "Unidades"),
    ("unitats", "unidades"),
    ("Tema", "Tema"),
    ("tema", "tema"),
    ("Lliçó", "Lección"),
    ("lliçó", "lección"),
    ("Classe", "Clase"),
    ("classe", "clase"),
    ("Classes", "Clases"),
    ("classes", "clases"),
    ("Continguts", "Contenidos"),
    ("continguts", "contenidos"),
    ("Bloc", "Bloque"),
    ("bloc", "bloque"),
    ("Blocs", "Bloques"),
    ("blocs", "bloques"),
    ("Diagrama d'arbre", "Diagrama de árbol"),
    ("diagrama d'arbre", "diagrama de árbol"),
    ("Diagrama de Venn", "Diagrama de Venn"),
    ("Estratègia", "Estrategia"),
    ("estratègia", "estrategia"),
    ("Mètode", "Método"),
    ("mètode", "método"),
    ("Truc", "Truco"),
    ("truc", "truco"),
    ("Idea", "Idea"),
    ("Mira", "Mira"),
    ("Hi ha", "Hay"),
    ("hi ha", "hay"),
    ("amb", "con"),
    ("Amb", "Con"),
    ("dels", "de los"),
    ("Dels", "De los"),
    ("dels apunts", "de los apuntes"),
    ("dels exercicis", "de los ejercicios"),
    ("dels alumnes", "de los alumnos"),
    ("alumnes", "alumnos"),
    ("Alumnes", "Alumnos"),
    ("Setmana", "Semana"),
    ("setmana", "semana"),
    ("Dia", "Día"),
    ("dia", "día"),
    ("Avui", "Hoy"),
    ("avui", "hoy"),
    ("Ahir", "Ayer"),
    ("ahir", "ayer"),
    ("Demà", "Mañana"),
    ("demà", "mañana"),
    ("Volem", "Queremos"),
    ("volem", "queremos"),
    ("Sabem", "Sabemos"),
    ("sabem", "sabemos"),
    ("Diem", "Decimos"),
    ("diem", "decimos"),
    ("Llavors diem", "Entonces decimos"),
    ("on", "donde"),
    ("On", "Donde"),
    ("d'una", "de una"),
    ("d'un", "de un"),
    ("d'on", "de donde"),
    ("D'un", "De un"),
    ("D'una", "De una"),
    ("d'exemple", "de ejemplo"),
    ("d'aquesta", "de esta"),
    ("d'aquest", "de este"),
    ("d'aquestes", "de estas"),
    ("d'aquests", "de estos"),
    ("l'experiment", "el experimento"),
    ("l'espai", "el espacio"),
    ("l'esdeveniment", "el evento"),
    ("l'altre", "el otro"),
    ("l'altra", "la otra"),
    ("l'alumne", "el alumno"),
    ("l'alumnat", "el alumnado"),
    ("l'institut", "el instituto"),
    ("l'antiimatge", "la antiimagen"),
    ("L'experiment", "El experimento"),
    ("L'espai", "El espacio"),
    ("Llistat", "Listado"),
    ("llistat", "listado"),
    ("Index", "Índice"),
    ("Índex", "Índice"),
    ("índex", "índice"),
    ("Inici", "Inicio"),
    ("Docència", "Docencia"),
    ("Doctorat", "Doctorado"),
    ("Notes", "Notas"),
    ("Contacte", "Contacto"),
    ("Llibre", "Libro"),
    ("llibre", "libro"),
    ("Fitxa", "Ficha"),
    ("fitxa", "ficha"),
    ("Fitxes", "Fichas"),
    ("fitxes", "fichas"),
    ("Examen", "Examen"),
    ("Exàmens", "Exámenes"),
    ("exàmens", "exámenes"),
    ("Parcial", "Parcial"),
    ("Evaluació", "Evaluación"),
    ("Avaluació", "Evaluación"),
    ("avaluació", "evaluación"),
    ("Trimestre", "Trimestre"),
    ("trimestre", "trimestre"),
    ("setembre", "septiembre"),
    ("Setembre", "Septiembre"),
    ("octubre", "octubre"),
    ("Octubre", "Octubre"),
    ("novembre", "noviembre"),
    ("Novembre", "Noviembre"),
    ("desembre", "diciembre"),
    ("Desembre", "Diciembre"),
    ("gener", "enero"),
    ("Gener", "Enero"),
    ("febrer", "febrero"),
    ("Febrer", "Febrero"),
    ("març", "marzo"),
    ("Març", "Marzo"),
    ("abril", "abril"),
    ("Abril", "Abril"),
    ("maig", "mayo"),
    ("Maig", "Mayo"),
    ("juny", "junio"),
    ("Juny", "Junio"),
    ("juliol", "julio"),
    ("Juliol", "Julio"),
    ("agost", "agosto"),
    ("Agost", "Agosto"),
    # Abreviados de meses
    ("gen ", "ene "),
    ("febr", "feb"),
    ("març", "mar"),
    ("abr ", "abr "),
    ("maig", "may"),
    ("juny", "jun"),
    ("jul ", "jul "),
    ("ago ", "ago "),
    ("set ", "sep "),
    ("oct ", "oct "),
    ("nov ", "nov "),
    ("des ", "dic "),
    # Conjunciones
    (" i ", " y "),
    (" o ", " o "),  # igual
    (" o, ", " o, "),  # igual
    # Otros comunes
    ("Recordatori", "Recordatorio"),
    ("recordatori", "recordatorio"),
    ("Drecera", "Atajo"),
    ("drecera", "atajo"),
]


# Patrón para preservar LaTeX entre $...$ y $$...$$
LATEX_RE = re.compile(r'(\$\$[^$]+\$\$|\$[^$\n]+\$)')
# Patrón para tags HTML completos (preserva atributos como class, href, id)
HTML_TAG_RE = re.compile(r'(<[^>]+>)')


def split_preserve(text):
    """Divide el texto en segmentos: protegidos (LaTeX, HTML tag) y traducibles."""
    # Primero protegemos las matemáticas
    parts = []
    last = 0
    for m in LATEX_RE.finditer(text):
        if m.start() > last:
            parts.append(("text", text[last:m.start()]))
        parts.append(("protected", m.group(0)))
        last = m.end()
    if last < len(text):
        parts.append(("text", text[last:]))

    # Ahora dentro de los "text" preservamos las tags HTML
    result = []
    for kind, segment in parts:
        if kind == "protected":
            result.append(("protected", segment))
            continue
        sub_last = 0
        for tm in HTML_TAG_RE.finditer(segment):
            if tm.start() > sub_last:
                result.append(("text", segment[sub_last:tm.start()]))
            result.append(("protected", tm.group(0)))
            sub_last = tm.end()
        if sub_last < len(segment):
            result.append(("text", segment[sub_last:]))
    return result


def translate_text(s):
    """Aplica el glosario a un fragmento de texto."""
    for ca, es in GLOSSARY:
        s = s.replace(ca, es)
    return s


def translate_html(content):
    """Procesa el HTML completo aplicando traducción solo a los fragmentos de texto."""
    parts = split_preserve(content)
    out = []
    for kind, segment in parts:
        if kind == "protected":
            out.append(segment)
        else:
            out.append(translate_text(segment))
    return "".join(out)


def main():
    n_translated = 0
    n_skipped = 0
    for html in REPO_ROOT.rglob("*.html"):
        rel = html.relative_to(REPO_ROOT)
        if rel.parts[0] in SKIP_TOP:
            continue
        try:
            text = html.read_text(encoding="utf-8")
        except Exception:
            continue

        # Solo procesamos los que tienen lang="ca"
        m = re.search(r'<html\s+lang="([^"]+)"', text)
        if not m or m.group(1) != "ca":
            n_skipped += 1
            continue

        # Traducir contenido + cambiar lang
        new_text = translate_html(text)
        new_text = re.sub(r'<html\s+lang="ca"', '<html lang="es"', new_text, count=1)

        if new_text == text:
            n_skipped += 1
            continue

        if DRY_RUN:
            print(f"  [dry-run] {rel}")
        else:
            html.write_text(new_text, encoding="utf-8")
            print(f"  ✓ {rel}")
        n_translated += 1

    print("")
    print("─── Resumen ───")
    if DRY_RUN:
        print(f"  [dry-run] Habría traducido: {n_translated}")
    else:
        print(f"  ✓ Traducidos: {n_translated}")
    print(f"  · Saltados: {n_skipped}")


if __name__ == "__main__":
    main()
